server:
  port: 9090

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:


    gateway:
      discovery:
        locator:
          enable: true
      routes:

        - id: ms-persona-service
          uri: lb://ms-persona-service
          predicates:
            - Path=/persona/**

        - id: ms-usuario-service
          uri: lb://ms-usuario-service
          predicates:
            - Path=/usuario/**

        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

        - id: ms-calendarioAcademico-service
          uri: lb://ms-calendarioAcademico-service
          predicates:
            - Path=/calendarioAcademico/**

        - id: ms-carrera-service
          uri: lb://ms-carrera-service
          predicates:
            - Path=/carrera/**

        - id: ms-curso-service
          uri: lb://ms-curso-service
          predicates:
            - Path=/curso/**

        - id: ms-docente-service
          uri: lb://ms-docente-service
          predicates:
            - Path=/docente/**

        - id: ms-estudiante-service
          uri: lb://ms-estudiante-service
          predicates:
            - Path=/estudiante/**

        - id: ms-evaluacionAcademica-service
          uri: lb://ms-evaluacionAcademica-service
          predicates:
            - Path=/evaluacionAcademica/**

        - id: ms-materialesEducativos-service
          uri: lb://ms-materialesEducativos-service
          predicates:
            - Path=/materialesEducativos/**

        - id: ms-planificacionAcademica-service
          uri: lb://ms-planificacionAcademica-service
          predicates:
            - Path=/planificacionAcademica/**