server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:

      discovery:
        locator:
          enable: true

      routes:
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**, /api/email/**

        - id: ms-roles-service
          uri: lb://ms-roles-service
          predicates:
            - Path=/rol/**

        - id: ms-usuarios-service
          uri: lb://ms-usuarios-service
          predicates:
            - Path=/usuario/**

        - id: ms-realTimeChat-service
          uri: lb://ms-realTimeChat-service
          predicates:
            - Path=/ws/**

        - id: ms-persona-service
          uri: lb://ms-persona-service
          predicates:
            - Path=/persona/**
          filters:
            - AuthFilter

        - id: ms-administrador-service
          uri: lb://ms-administrador-service
          predicates:
            - Path=/administrador/**
          filters:
            - AuthFilter

        - id: ms-inscripciones-service
          uri: lb://ms-inscripciones-service
          predicates:
            - Path=/inscripcion/**
          filters:
            - AuthFilter

        - id: ms-calendarioAcademico-service
          uri: lb://ms-calendarioAcademico-service
          predicates:
            - Path=/calendarioAcademico/**
          filters:
            - AuthFilter

        - id: ms-carrera-service
          uri: lb://ms-carrera-service
          predicates:
            - Path=/carrera/**
          filters:
            - AuthFilter

        - id: ms-curso-service
          uri: lb://ms-curso-service
          predicates:
            - Path=/curso/**
          filters:
            - AuthFilter

        - id: ms-docente-service
          uri: lb://ms-docente-service
          predicates:
            - Path=/docente/**
          filters:
            - AuthFilter

        - id: ms-estudiante-service
          uri: lb://ms-estudiante-service
          predicates:
            - Path=/estudiante/**
          filters:
            - AuthFilter

        - id: ms-administrativo-service
          uri: lb://ms-administrativo-service
          predicates:
            - Path=/administrativo/**
          filters:
            - AuthFilter

        - id: ms-evaluacionAcademica-service
          uri: lb://ms-evaluacionAcademica-service
          predicates:
            - Path=/evaluacionAcademica/**
          filters:
            - AuthFilter

        - id: ms-materialesEducativos-service
          uri: lb://ms-materialesEducativos-service
          predicates:
            - Path=/materialesEducativos/**
          filters:
            - AuthFilter

        - id: ms-planificacionAcademica-service
          uri: lb://ms-planificacionAcademica-service
          predicates:
            - Path=/planificacionAcademica/**
          filters:
            - AuthFilter

      globalcors:
        corsConfigurations:
          '/auth/**': # Aplicar la configuración a las rutas que empiecen con "/auth"
            allowedOrigins:
              - "http://localhost:3000"  # Permitir el frontend en desarrollo local
            allowedHeaders:
              - "*"  # Permitir todos los encabezados, incluyendo Authorization
            allowedMethods:
              - "*"  # Permitir todos los métodos (GET, POST, PUT, DELETE, OPTIONS)
            allowCredentials: true  # Permitir el envío de credenciales

          '/api/email/**': # Aplicar la configuración a las rutas que empiecen con "/api/email"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/rol/**': # Aplicar la configuración a las rutas que empiecen con "/rol"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/usuario/**': # Aplicar la configuración a las rutas que empiecen con "/usuario"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/persona/**': # Aplicar la configuración a las rutas que empiecen con "/persona"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/administrador/**': # Aplicar la configuración a las rutas que empiecen con "/administrador"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/inscripcion/**': # Aplicar la configuración a las rutas que empiecen con "/inscripcion"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/calendarioAcademico/**': # Aplicar la configuración a las rutas que empiecen con "/calendarioAcademico"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/carrera/**': # Aplicar la configuración a las rutas que empiecen con "/carrera"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/curso/**': # Aplicar la configuración a las rutas que empiecen con "/curso"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/docente/**': # Aplicar la configuración a las rutas que empiecen con "/docente"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/estudiante/**': # Aplicar la configuración a las rutas que empiecen con "/estudiante"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/administrativo/**': # Aplicar la configuración a las rutas que empiecen con "/administrativo"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/evaluacionAcademica/**': # Aplicar la configuración a las rutas que empiecen con "/evaluacionAcademica"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/materialesEducativos/**': # Aplicar la configuración a las rutas que empiecen con "/materialesEducativos"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

          '/planificacionAcademica/**': # Aplicar la configuración a las rutas que empiecen con "/planificacionAcademica"
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "*"
            allowCredentials: true

logging:
  level:
    org.springframework.web: DEBUG