server:
  port: 9090


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:


    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-persona-service
          uri: lb://ms-persona-service
          predicates:
            - Path=/persona/**
