server:
  #port: 8086
  port: ${PORT:${SERVER_PORT:0}} #Local

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /inscripciones/swagger-ui.html
spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms-inscripciones
    username: root
    password: 1234

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka} #Local
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

resilience4j.circuitbreaker:
  instances:
    #CIRCUITBREAKER CRUD ROL
    crearRolCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    listarRolesCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 10s
      failureRateThreshold: 60
      eventConsumerBufferSize: 10

    listarRolPorIdCB:
      registerHealthIndicator: true
      slidingWindowSize: 15
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 8s
      failureRateThreshold: 70
      eventConsumerBufferSize: 20

    actualizarRolCB:
      registerHealthIndicator: true
      slidingWindowSize: 20
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 12s
      failureRateThreshold: 50
      eventConsumerBufferSize: 15

    eliminarRolCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 7s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    #CIRCUITBREAKER CRUD USUARIO
    crearUsuarioCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    listarUsuariosCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 10s
      failureRateThreshold: 60
      eventConsumerBufferSize: 10

    listrUsuarioPorIdCB:
      registerHealthIndicator: true
      slidingWindowSize: 15
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 8s
      failureRateThreshold: 70
      eventConsumerBufferSize: 20

    actualizarUsuarioCB:
      registerHealthIndicator: true
      slidingWindowSize: 20
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 12s
      failureRateThreshold: 50
      eventConsumerBufferSize: 15

    eliminarUsuarioCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 7s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    #CIRCUITBREAKER CRUD PERSONA
    crearPersonaCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    listarPersonasCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 10s
      failureRateThreshold: 60
      eventConsumerBufferSize: 10

    listarPersonaPorIdCB:
      registerHealthIndicator: true
      slidingWindowSize: 15
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 8s
      failureRateThreshold: 70
      eventConsumerBufferSize: 20

    actualizarPersonaCB:
      registerHealthIndicator: true
      slidingWindowSize: 20
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 6
      waitDurationInOpenState: 12s
      failureRateThreshold: 50
      eventConsumerBufferSize: 15

    eliminarPersonaCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 7s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    #CIRCUITBREAKER CRUD ADMINISTRADOR
    crearAdministradorCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    listarAdminstradoresCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 10s
      failureRateThreshold: 60
      eventConsumerBufferSize: 10

    listarAdministradorPorIdCB:
      registerHealthIndicator: true
      slidingWindowSize: 15
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 8s
      failureRateThreshold: 70
      eventConsumerBufferSize: 20

    actualizarAdministradorCB:
      registerHealthIndicator: true
      slidingWindowSize: 20
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 6
      waitDurationInOpenState: 12s
      failureRateThreshold: 50
      eventConsumerBufferSize: 15

    eliminarAdministradorCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 7s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    #CIRCUITBREAKER CRUD ADMINISTRATIVO
    crearAdministrativoCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    listarAdministrativosCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 10s
      failureRateThreshold: 60
      eventConsumerBufferSize: 10

    listarAdministrativoPorIdCB:
      registerHealthIndicator: true
      slidingWindowSize: 15
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 8s
      failureRateThreshold: 70
      eventConsumerBufferSize: 20

    actualizarAdministrativoCB:
      registerHealthIndicator: true
      slidingWindowSize: 20
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 6
      waitDurationInOpenState: 12s
      failureRateThreshold: 50
      eventConsumerBufferSize: 15

    eliminarAdministrativoCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 7s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    #CIRCUITBREAKER CRUD DOCENTE
    crearDocenteCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    listarDocentesCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 10s
      failureRateThreshold: 60
      eventConsumerBufferSize: 10

    listarDocentePorIdCB:
      registerHealthIndicator: true
      slidingWindowSize: 15
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 8s
      failureRateThreshold: 70
      eventConsumerBufferSize: 20

    actualizarDocenteCB:
      registerHealthIndicator: true
      slidingWindowSize: 20
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 6
      waitDurationInOpenState: 12s
      failureRateThreshold: 50
      eventConsumerBufferSize: 15

    eliminarDocenteCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 7s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    #CIRCUITBREAKER CRUD ESTUDIANTE
    crearEstudianteCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

    listarEstudiantesCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 10s
      failureRateThreshold: 60
      eventConsumerBufferSize: 10

    listarEstudiantePorIdCB:
      registerHealthIndicator: true
      slidingWindowSize: 15
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 8s
      failureRateThreshold: 70
      eventConsumerBufferSize: 20

    actualizarEstudianteCB:
      registerHealthIndicator: true
      slidingWindowSize: 20
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 6
      waitDurationInOpenState: 12s
      failureRateThreshold: 50
      eventConsumerBufferSize: 15

    eliminarEstudianteCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 7s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10