server:
  #port: 8180
  port: ${PORT:${SERVER_PORT:0}} #Local

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /roles/swagger-ui.html
spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms-roles
    username: root
    password: 1234

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      #defaultZone: ${EUREKA_URI:http://localhost:8090/eureka} #Local
      defaultZone: ${EUREKA_URI:https://eleven-news-join.loca.lt:9090/eureka}

  instance:
    #hostname: localhost
    hostname: eleven-news-join.loca.lt  # Con dominio público
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}